name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ruby:3.3
    steps:
      - uses: actions/checkout@v4
      - run: bundle install
      - run: bundle exec rubocop
  test:
    needs: lint
    strategy:
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3]
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - run: bundle install
      - run: bundle exec rspec
